// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

import frc.robot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import frc.robot.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton joyLeftBtn2;
    public JoystickButton joyLeftBtn3;
    public JoystickButton joyLeftBtn4;
    public JoystickButton joyLeftBtn5;
    public JoystickButton joyLeftBtn6;
    public JoystickButton joyLeftBtn7;
    public JoystickButton joyLeftBtn8;
    public JoystickButton joyLeftBtn9;
    public JoystickButton joyLeftBtn10;
    public Joystick joyLeft;
    public JoystickButton joyRightBtn2;
    public JoystickButton joyRightBtn3;
    public JoystickButton joyRightBtn6;
    public JoystickButton joyRightBtn7;
    public Joystick joyRight;
    public JoystickButton gamepadA;
    public JoystickButton gamepadB;
    public JoystickButton gamepadX;
    public JoystickButton gamepadLB;
    public JoystickButton gamepadRB;
    public JoystickButton gamepadBack;
    public JoystickButton gamePadStart;
    public JoystickButton gamepadLS;
    public JoystickButton gamepadRS;
    public Joystick gamepad;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        gamepad = new Joystick(2);
        
        gamepadRS = new JoystickButton(gamepad, 10);
        gamepadRS.whenPressed(new HingeMoveUpOrDown());
        gamepadLS = new JoystickButton(gamepad, 9);
        gamepadLS.whenPressed(new ElevatorMoveUpOrDown());
        gamePadStart = new JoystickButton(gamepad, 8);
        gamePadStart.whenPressed(new HingeHome());
        gamepadBack = new JoystickButton(gamepad, 7);
        gamepadBack.whenPressed(new ElevatorHome());
        gamepadRB = new JoystickButton(gamepad, 6);
        gamepadRB.whenPressed(new HingeMoveMidway());
        gamepadLB = new JoystickButton(gamepad, 5);
        gamepadLB.whenPressed(new ElevatorMoveMidway());
        gamepadX = new JoystickButton(gamepad, 3);
        gamepadX.whenPressed(new HingeElevatorAndGrasperStop());
        gamepadB = new JoystickButton(gamepad, 2);
        gamepadB.whenPressed(new GrasperRelease());
        gamepadA = new JoystickButton(gamepad, 1);
        gamepadA.whenPressed(new GrasperGrasp());
        joyRight = new Joystick(0);
        
        joyRightBtn7 = new JoystickButton(joyRight, 7);
        joyRightBtn7.whenPressed(new BothDrivetrainsStop());
        joyRightBtn6 = new JoystickButton(joyRight, 6);
        joyRightBtn6.whenPressed(new BothDrivetrainsResetEncoders());
        joyRightBtn3 = new JoystickButton(joyRight, 3);
        joyRightBtn3.whenPressed(new JackSetPosition(0));
        joyRightBtn2 = new JoystickButton(joyRight, 2);
        joyRightBtn2.whenPressed(new JackSetPosition(0));
        joyLeft = new Joystick(1);
        
        joyLeftBtn10 = new JoystickButton(joyLeft, 10);
        joyLeftBtn10.whileHeld(new GrasperJoystickControl());
        joyLeftBtn9 = new JoystickButton(joyLeft, 9);
        joyLeftBtn9.whileHeld(new HingeJoystickControl());
        joyLeftBtn8 = new JoystickButton(joyLeft, 8);
        joyLeftBtn8.whileHeld(new ElevatorJoystickControl());
        joyLeftBtn7 = new JoystickButton(joyLeft, 7);
        joyLeftBtn7.whenPressed(new BothDrivetrainsStop());
        joyLeftBtn6 = new JoystickButton(joyLeft, 6);
        joyLeftBtn6.whenPressed(new BothDrivetrainsAndGyroReset());
        joyLeftBtn5 = new JoystickButton(joyLeft, 5);
        joyLeftBtn5.whenPressed(new DrivetrainTurnAngleUsingPidController(0));
        joyLeftBtn4 = new JoystickButton(joyLeft, 4);
        joyLeftBtn4.whenPressed(new DrivetrainTurnAngleUsingPidController(0));
        joyLeftBtn3 = new JoystickButton(joyLeft, 3);
        joyLeftBtn3.whenPressed(new CurrentDrivetrainMoveDistance());
        joyLeftBtn2 = new JoystickButton(joyLeft, 2);
        joyLeftBtn2.whenPressed(new MiniDriveTrainMoveUsingCameraPidController());


        // SmartDashboard Buttons

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getjoyLeft() {
        return joyLeft;
    }

    public Joystick getjoyRight() {
        return joyRight;
    }

    public Joystick getgamepad() {
        return gamepad;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

